export const ORDER_CREATE_REQUEST = "OREDER_CREATE_REQUEST";
export const ORDER_CREATE_SUCCESS = "OREDER_CREATE_SUCCESS";
export const ORDER_CREATE_FAIL = "OREDER_CREATE_FAIL";

export const ORDER_DETAILS_REQUEST = "OREDER_DETAILS_REQUEST";
export const ORDER_DETAILS_SUCCESS = "OREDER_DETAILS_SUCCESS";
export const ORDER_DETAILS_FAIL = "OREDER_DETAILS_FAIL";

export const ORDER_PAY_REQUEST = "OREDER_PAY_REQUEST";
export const ORDER_PAY_SUCCESS = "OREDER_PAY_SUCCESS";
export const ORDER_PAY_FAIL = "OREDER_PAY_FAIL";
export const ORDER_PAY_RESET = "OREDER_PAY_RESET";

export const ORDER_LIST_MY_REQUEST = "OREDER_LIST_MY_REQUEST";
export const ORDER_LIST_MY_SUCCESS = "OREDER_LIST_MY_SUCCESS";
export const ORDER_LIST_MY_FAIL = "OREDER_LIST_MY_FAIL";
export const ORDER_LIST_MY_RESET = "OREDER_LIST_MY_RESET";

export const ORDER_LIST_REQUEST = "OREDER_LIST_REQUEST";
export const ORDER_LIST_SUCCESS = "OREDER_LIST_SUCCESS";
export const ORDER_LIST_FAIL = "OREDER_LIST_FAIL";

export const ORDER_DELIVER_REQUEST = "OREDER_DELIVER_REQUEST";
export const ORDER_DELIVER_SUCCESS = "OREDER_DELIVER_SUCCESS";
export const ORDER_DELIVER_FAIL = "OREDER_DELIVER_FAIL";
export const ORDER_DELIVER_RESET = "OREDER_DELIVER_RESET";
